# pyequa defaults



answer_template: |
  Knowing

  {localgivenvars}

  and using

  {solvers}

  it can be found

  {localrequestedvars}




# 
student_feedback: |
  
  (No feedback is available. Please consult your class teacher(s).)



# Output destination of the produced exercises
output_service: moodle_cloze
output_extension: md #output to a markdown file


# In a folder, the standard filename for anexercise template
student_template_filename: exercise_model.md

# CSV as a standard format
dataframe_type: csv  #csv or xlsx
csv_separator: "," 
csv_decimal: "." 


author: author


# challenge vs exam 
gen_method: challenge

# when gen_method is 'challenge'
# number of variants of the same exercise model
number_of_variants_per_exercise: 1 

# when gen_method is 'exam' 
number_of_given_vars: 1 

# when gen_method is 'all'
# TODO

several_solutions: " (more than one solution; choose one) "
global_tolerance: 0.001

# output a knowledge graph
output_knowledge_graph: false






