---
title: "dados-study.Rmd"
author: "Pedro Cruz"
date: "2025-02-28_11-25-53"
output:
  html_document: default
---


# Model dados-study.Rmd - CLOZE



## variante 001 (data row is 01)


Considere o sistema de equações de variáveis reais:

\(
\begin{cases}
2a+b+c = 0\\
a+b=10\\
\end{cases}
\)

Assim,

* a = **0**
* b = **10**
* c = {:NUMERICAL:%100%-10:0.01}

(Valores arredondados até 2 casas decimais, se necessário.)
### feedback



(Consulte o docente.)




## variante 002 (data row is 02)


Considere o sistema de equações de variáveis reais:

\(
\begin{cases}
2a+b+c = 0\\
a+b=10\\
\end{cases}
\)

Assim,

* a = {:NUMERICAL:%100%1:0.01}
* b = **9**
* c = **-10**

(Valores arredondados até 2 casas decimais, se necessário.)
### feedback



(Consulte o docente.)




## variante 003 (data row is 03)


Considere o sistema de equações de variáveis reais:

\(
\begin{cases}
2a+b+c = 0\\
a+b=10\\
\end{cases}
\)

Assim,

* a = **3**
* b = {:NUMERICAL:%100%7:0.01}
* c = **-8**

(Valores arredondados até 2 casas decimais, se necessário.)
### feedback



(Consulte o docente.)




## variante 004 (data row is 01)


Considere o sistema de equações de variáveis reais:

\(
\begin{cases}
2a+b+c = 0\\
a+b=10\\
\end{cases}
\)

Assim,

* a = {:NUMERICAL:%100%0:0.01}
* b = **10**
* c = {:NUMERICAL:%100%-10:0.01}

(Valores arredondados até 2 casas decimais, se necessário.)
### feedback



(Consulte o docente.)




## variante 005 (data row is 02)


Considere o sistema de equações de variáveis reais:

\(
\begin{cases}
2a+b+c = 0\\
a+b=10\\
\end{cases}
\)

Assim,

* a = **1**
* b = {:NUMERICAL:%100%9:0.01}
* c = {:NUMERICAL:%100%-10:0.01}

(Valores arredondados até 2 casas decimais, se necessário.)
### feedback



(Consulte o docente.)




## variante 006 (data row is 03)


Considere o sistema de equações de variáveis reais:

\(
\begin{cases}
2a+b+c = 0\\
a+b=10\\
\end{cases}
\)

Assim,

* a = {:NUMERICAL:%100%3:0.01}
* b = {:NUMERICAL:%100%7:0.01}
* c = **-8**

(Valores arredondados até 2 casas decimais, se necessário.)
### feedback



(Consulte o docente.)


