
---
title: "df_sc_or_s-study.Rmd"
author: "(author)"
date: "2025-01-22_14-40-03"
output:
  html_document: default
---


# Model df_sc_or_s-study.Rmd - CLOZE



## variante 001 (data row is 01)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\),  \(E[s_c] = \sigma\).

Considere uma amostra de tamanho **'2'**.

**(a)** Verifique que para essa amostra a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = **1.414** \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com essa amostra, {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão **corrigido** pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.
### feedback

(Consulte o docente das suas turmas ou uma OT.)


## variante 002 (data row is 02)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\),  \(E[s_c] = \sigma\).

Considere uma amostra de tamanho **'4'**.

**(a)** Verifique que para essa amostra a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = **1.155** \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com essa amostra, **deve** ser usado o desvio padrão **corrigido** pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.
### feedback

(Consulte o docente das suas turmas ou uma OT.)


## variante 003 (data row is 03)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\),  \(E[s_c] = \sigma\).

Considere uma amostra de tamanho **'10'**.

**(a)** Verifique que para essa amostra a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = **1.054** \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com essa amostra, {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão **corrigido** pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.
### feedback

(Consulte o docente das suas turmas ou uma OT.)


## variante 004 (data row is 04)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\),  \(E[s_c] = \sigma\).

Considere uma amostra de tamanho **'20'**.

**(a)** Verifique que para essa amostra a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = **1.026** \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com essa amostra, {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.
### feedback

(Consulte o docente das suas turmas ou uma OT.)


## variante 005 (data row is 05)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\),  \(E[s_c] = \sigma\).

Considere uma amostra de tamanho **'100'**.

**(a)** Verifique que para essa amostra a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = **1.005** \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com essa amostra, {:MULTICHOICE_S:%0%deve\~%100%pode} ser usado o desvio padrão {:MULTICHOICE_S:%0%corrigido\~%100%corrigido ou não} pois o desvio padrão corrigido é {:MULTICHOICE_S:%0%maior, ou bastante maior, que o\~%100%aproximado ao} desvio padrão não corrigido.
### feedback

(Consulte o docente das suas turmas ou uma OT.)


## variante 006 (data row is 06)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\),  \(E[s_c] = \sigma\).

Considere uma amostra de tamanho **'1000'**.

**(a)** Verifique que para essa amostra a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = {:NUMERICAL:%100%1.001:0.01} \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com essa amostra, {:MULTICHOICE_S:%0%deve\~%100%pode} ser usado o desvio padrão **corrigido ou não** pois o desvio padrão corrigido é {:MULTICHOICE_S:%0%maior, ou bastante maior, que o\~%100%aproximado ao} desvio padrão não corrigido.
### feedback

(Consulte o docente das suas turmas ou uma OT.)


## variante 007 (data row is 01)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\),  \(E[s_c] = \sigma\).

Considere uma amostra de tamanho **'2'**.

**(a)** Verifique que para essa amostra a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = {:NUMERICAL:%100%1.414:0.01} \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com essa amostra, {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.
### feedback

(Consulte o docente das suas turmas ou uma OT.)


## variante 008 (data row is 02)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\),  \(E[s_c] = \sigma\).

Considere uma amostra de tamanho {:MULTICHOICE_S:%0%'2'\~%100%'4'\~%0%'10'\~%0%'20'\~%0%'100'\~%0%'1000'}.

**(a)** Verifique que para essa amostra a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = **1.155** \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com essa amostra, {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.
### feedback

(Consulte o docente das suas turmas ou uma OT.)
