# Model C:\Users\pedrocruz\Documents\GitHub\pyequa\examples\cloze\_output_

Produced in 2024-11-20 16:07:50

# Problem 01 - CLOZE

## variante 01 (excel row is 001)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), **deve** ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} 
pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.

### feedback

(Consulte o docente das suas turmas ou uma OT.)


## variante 02 (excel row is 002)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), **deve** ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} 
pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.

### feedback

(Consulte o docente das suas turmas ou uma OT.)

# Problem 02 - CLOZE

## variante 01 (excel row is 003)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), **deve** ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

### feedback

(Consulte o docente das suas turmas ou uma OT.)


## variante 02 (excel row is 004)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), **deve** ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

### feedback

(Consulte o docente das suas turmas ou uma OT.)

# Problem 03 - CLOZE

## variante 01 (excel row is 005)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho **'100'**, **pode** ser usado o desvio padrão {:MULTICHOICE_S:%0%corrigido\~%100%corrigido ou não} 
pois o desvio padrão corrigido é **aproximado ao** desvio padrão não corrigido.

### feedback

(Consulte o docente das suas turmas ou uma OT.)


## variante 02 (excel row is 006)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho **'1000'**, **pode** ser usado o desvio padrão {:MULTICHOICE_S:%0%corrigido\~%100%corrigido ou não} 
pois o desvio padrão corrigido é **aproximado ao** desvio padrão não corrigido.

### feedback

(Consulte o docente das suas turmas ou uma OT.)

# Problem 04 - CLOZE

## variante 01 (excel row is 001)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho **'2'**, **deve** ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

### feedback

(Consulte o docente das suas turmas ou uma OT.)


## variante 02 (excel row is 002)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho **'4'**, **deve** ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

### feedback

(Consulte o docente das suas turmas ou uma OT.)

# Problem 05 - CLOZE

## variante 01 (excel row is 003)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), **deve** ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.

### feedback

(Consulte o docente das suas turmas ou uma OT.)


## variante 02 (excel row is 004)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), **deve** ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.

### feedback

(Consulte o docente das suas turmas ou uma OT.)

# Problem 06 - CLOZE

## variante 01 (excel row is 005)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho **'100'**, **pode** ser usado o desvio padrão **corrigido ou não** 
pois o desvio padrão corrigido é **aproximado ao** desvio padrão não corrigido.

### feedback

(Consulte o docente das suas turmas ou uma OT.)


## variante 02 (excel row is 006)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho **'1000'**, **pode** ser usado o desvio padrão **corrigido ou não** 
pois o desvio padrão corrigido é **aproximado ao** desvio padrão não corrigido.

### feedback

(Consulte o docente das suas turmas ou uma OT.)

# Problem 01 - CLOZE

## variante 01 (excel row is 001)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), **deve** ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} 
pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.

### feedback

(Consulte o docente das suas turmas ou uma OT.)


## variante 02 (excel row is 002)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), **deve** ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} 
pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.

### feedback

(Consulte o docente das suas turmas ou uma OT.)

# Problem 02 - CLOZE

## variante 01 (excel row is 003)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), **deve** ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

### feedback

(Consulte o docente das suas turmas ou uma OT.)


## variante 02 (excel row is 004)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), **deve** ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

### feedback

(Consulte o docente das suas turmas ou uma OT.)

# Problem 03 - CLOZE

## variante 01 (excel row is 005)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho **'100'**, **pode** ser usado o desvio padrão {:MULTICHOICE_S:%0%corrigido\~%100%corrigido ou não} 
pois o desvio padrão corrigido é **aproximado ao** desvio padrão não corrigido.

### feedback

(Consulte o docente das suas turmas ou uma OT.)


## variante 02 (excel row is 006)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho **'1000'**, **pode** ser usado o desvio padrão {:MULTICHOICE_S:%0%corrigido\~%100%corrigido ou não} 
pois o desvio padrão corrigido é **aproximado ao** desvio padrão não corrigido.

### feedback

(Consulte o docente das suas turmas ou uma OT.)

# Problem 04 - CLOZE

## variante 01 (excel row is 001)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho **'2'**, **deve** ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

### feedback

(Consulte o docente das suas turmas ou uma OT.)


## variante 02 (excel row is 002)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho **'4'**, **deve** ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

### feedback

(Consulte o docente das suas turmas ou uma OT.)

# Problem 05 - CLOZE

## variante 01 (excel row is 003)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), **deve** ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.

### feedback

(Consulte o docente das suas turmas ou uma OT.)


## variante 02 (excel row is 004)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), **deve** ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.

### feedback

(Consulte o docente das suas turmas ou uma OT.)

# Problem 01 - CLOZE

## variante 01 (excel row is 001)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), **deve** ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} 
pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.

### feedback

(Consulte o docente das suas turmas ou uma OT.)


## variante 02 (excel row is 002)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), **deve** ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} 
pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.

### feedback

(Consulte o docente das suas turmas ou uma OT.)

# Problem 02 - CLOZE

## variante 01 (excel row is 003)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), **deve** ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

### feedback

(Consulte o docente das suas turmas ou uma OT.)


## variante 02 (excel row is 004)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), **deve** ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

### feedback

(Consulte o docente das suas turmas ou uma OT.)

