# Solution to model C:\Users\pedrocruz\Documents\GitHub\pyequa\examples\cloze\_output_

Produced in 2024-10-28 21:07:17

# Problem 01 - CLOZE

## variante 01 (excel row is 001)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional.

Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), deve ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

## answer

Com uma amostra de tamanho %100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000',  ser usado o desvio padrão %100%corrigido\~%0%corrigido ou não 
pois o desvio padrão corrigido é %100%maior, ou bastante maior, que o\~%0%aproximado ao desvio padrão não corrigido.


Sabendo

{podedeve}

e usando

Eq(podedeve, corrigido)

determina-se

{corrigido}

Sabendo

{podedeve, corrigido}

e usando

Eq(corrigido, justificação)

determina-se

{justificação}

Sabendo

{podedeve, corrigido, justificação}

e usando

Eq(tamanho, podedeve)

determina-se

{tamanho}



## variante 02 (excel row is 002)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional.

Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), deve ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

## answer

Com uma amostra de tamanho %100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000',  ser usado o desvio padrão %100%corrigido\~%0%corrigido ou não 
pois o desvio padrão corrigido é %100%maior, ou bastante maior, que o\~%0%aproximado ao desvio padrão não corrigido.


Sabendo

{podedeve}

e usando

Eq(podedeve, corrigido)

determina-se

{corrigido}

Sabendo

{podedeve, corrigido}

e usando

Eq(corrigido, justificação)

determina-se

{justificação}

Sabendo

{podedeve, corrigido, justificação}

e usando

Eq(tamanho, podedeve)

determina-se

{tamanho}


# Problem 02 - CLOZE

## variante 01 (excel row is 003)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional.

Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão corrigido 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

## answer

Com uma amostra de tamanho %100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000', %100%deve\~%0%pode ser usado o desvio padrão  
pois o desvio padrão corrigido é %100%maior, ou bastante maior, que o\~%0%aproximado ao desvio padrão não corrigido.


Sabendo

{corrigido}

e usando

Eq(corrigido, justificação)

determina-se

{justificação}

Sabendo

{corrigido, justificação}

e usando

Eq(podedeve, corrigido)

determina-se

{podedeve}

Sabendo

{podedeve, corrigido, justificação}

e usando

Eq(tamanho, podedeve)

determina-se

{tamanho}



## variante 02 (excel row is 004)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional.

Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão corrigido 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

## answer

Com uma amostra de tamanho %100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000', %100%deve\~%0%pode ser usado o desvio padrão  
pois o desvio padrão corrigido é %100%maior, ou bastante maior, que o\~%0%aproximado ao desvio padrão não corrigido.


Sabendo

{corrigido}

e usando

Eq(corrigido, justificação)

determina-se

{justificação}

Sabendo

{corrigido, justificação}

e usando

Eq(podedeve, corrigido)

determina-se

{podedeve}

Sabendo

{podedeve, corrigido, justificação}

e usando

Eq(tamanho, podedeve)

determina-se

{tamanho}


# Problem 03 - CLOZE

## variante 01 (excel row is 005)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional.

Com uma amostra de tamanho '100', {:MULTICHOICE_S:%0%deve\~%100%pode} ser usado o desvio padrão {:MULTICHOICE_S:%0%corrigido\~%100%corrigido ou não} 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%0%maior, ou bastante maior, que o\~%100%aproximado ao} desvio padrão não corrigido.

## answer

Com uma amostra de tamanho , %0%deve\~%100%pode ser usado o desvio padrão %0%corrigido\~%100%corrigido ou não 
pois o desvio padrão corrigido é %0%maior, ou bastante maior, que o\~%100%aproximado ao desvio padrão não corrigido.


Sabendo

{tamanho}

e usando

Eq(tamanho, podedeve)

determina-se

{podedeve}

Sabendo

{podedeve, tamanho}

e usando

Eq(podedeve, corrigido)

determina-se

{corrigido}

Sabendo

{podedeve, corrigido, tamanho}

e usando

Eq(corrigido, justificação)

determina-se

{justificação}



## variante 02 (excel row is 006)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional.

Com uma amostra de tamanho '1000', {:MULTICHOICE_S:%0%deve\~%100%pode} ser usado o desvio padrão {:MULTICHOICE_S:%0%corrigido\~%100%corrigido ou não} 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%0%maior, ou bastante maior, que o\~%100%aproximado ao} desvio padrão não corrigido.

## answer

Com uma amostra de tamanho , %0%deve\~%100%pode ser usado o desvio padrão %0%corrigido\~%100%corrigido ou não 
pois o desvio padrão corrigido é %0%maior, ou bastante maior, que o\~%100%aproximado ao desvio padrão não corrigido.


Sabendo

{tamanho}

e usando

Eq(tamanho, podedeve)

determina-se

{podedeve}

Sabendo

{podedeve, tamanho}

e usando

Eq(podedeve, corrigido)

determina-se

{corrigido}

Sabendo

{podedeve, corrigido, tamanho}

e usando

Eq(corrigido, justificação)

determina-se

{justificação}


# Problem 04 - CLOZE

## variante 01 (excel row is 001)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional.

Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} 
pois o desvio padrão corrigido é maior, ou bastante maior, que o desvio padrão não corrigido.

## answer

Com uma amostra de tamanho %100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000', %100%deve\~%0%pode ser usado o desvio padrão %100%corrigido\~%0%corrigido ou não 
pois o desvio padrão corrigido é  desvio padrão não corrigido.


Sabendo

{justificação}

e usando

Eq(corrigido, justificação)

determina-se

{corrigido}

Sabendo

{corrigido, justificação}

e usando

Eq(podedeve, corrigido)

determina-se

{podedeve}

Sabendo

{podedeve, corrigido, justificação}

e usando

Eq(tamanho, podedeve)

determina-se

{tamanho}



## variante 02 (excel row is 002)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional.

Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} 
pois o desvio padrão corrigido é maior, ou bastante maior, que o desvio padrão não corrigido.

## answer

Com uma amostra de tamanho %100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000', %100%deve\~%0%pode ser usado o desvio padrão %100%corrigido\~%0%corrigido ou não 
pois o desvio padrão corrigido é  desvio padrão não corrigido.


Sabendo

{justificação}

e usando

Eq(corrigido, justificação)

determina-se

{corrigido}

Sabendo

{corrigido, justificação}

e usando

Eq(podedeve, corrigido)

determina-se

{podedeve}

Sabendo

{podedeve, corrigido, justificação}

e usando

Eq(tamanho, podedeve)

determina-se

{tamanho}


