
---
title: "sc_or_s-study.Rmd"
author: "Pedro Cruz"
date: "2024-11-24_12-05-11"
output:
  html_document: default
---


# Model sc_or_s-study.Rmd - CLOZE


## variante 02 (excel row is 01)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho **'2'**, **deve** ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

Qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)

Sabendo

{tamanho, corrigido, podedeve}

e usando

Eq(tamanho, corrigido + justificação)

determina-se

{justificação}




## variante 03 (excel row is 02)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho **'4'**, **deve** ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

Qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)

Sabendo

{tamanho, corrigido, podedeve}

e usando

Eq(tamanho, corrigido + justificação)

determina-se

{justificação}




## variante 04 (excel row is 03)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho **'10'**, {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.

Qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)

Sabendo

{tamanho, corrigido, justificação}

e usando

Eq(tamanho, corrigido + podedeve)

determina-se

{podedeve}




## variante 05 (excel row is 04)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho **'20'**, {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.

Qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)

Sabendo

{tamanho, corrigido, justificação}

e usando

Eq(tamanho, corrigido + podedeve)

determina-se

{podedeve}




## variante 06 (excel row is 05)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho **'100'**, **pode** ser usado o desvio padrão {:MULTICHOICE_S:%0%corrigido\~%100%corrigido ou não} 
pois o desvio padrão corrigido é **aproximado ao** desvio padrão não corrigido.

Qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)

Sabendo

{tamanho, podedeve, justificação}

e usando

Eq(tamanho, corrigido + justificação)

determina-se

{corrigido}




## variante 07 (excel row is 06)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho **'1000'**, **pode** ser usado o desvio padrão {:MULTICHOICE_S:%0%corrigido\~%100%corrigido ou não} 
pois o desvio padrão corrigido é **aproximado ao** desvio padrão não corrigido.

Qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)

Sabendo

{tamanho, podedeve, justificação}

e usando

Eq(tamanho, corrigido + justificação)

determina-se

{corrigido}




## variante 08 (excel row is 01)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), **deve** ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.

Qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)

Sabendo

{corrigido, podedeve, justificação}

e usando

Eq(tamanho, corrigido + justificação)

determina-se

{tamanho}




## variante 09 (excel row is 02)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), **deve** ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.

Qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)

Sabendo

{corrigido, podedeve, justificação}

e usando

Eq(tamanho, corrigido + justificação)

determina-se

{tamanho}




## variante 02 (excel row is 01)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho **'2'**, {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

Qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)

Sabendo

{tamanho, corrigido}

e usando

Eq(tamanho, corrigido + podedeve)

determina-se

{podedeve}

Sabendo

{tamanho, corrigido, podedeve}

e usando

Eq(tamanho, corrigido + justificação)

determina-se

{justificação}




## variante 03 (excel row is 02)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho **'4'**, {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

Qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)

Sabendo

{tamanho, corrigido}

e usando

Eq(tamanho, corrigido + podedeve)

determina-se

{podedeve}

Sabendo

{tamanho, corrigido, podedeve}

e usando

Eq(tamanho, corrigido + justificação)

determina-se

{justificação}




## variante 04 (excel row is 03)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho **'10'**, **deve** ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

Qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)

Sabendo

{tamanho, podedeve}

e usando

Eq(tamanho, justificação)

determina-se

{justificação}

Sabendo

{tamanho, podedeve, justificação}

e usando

Eq(tamanho, corrigido + justificação)

determina-se

{corrigido}




## variante 05 (excel row is 04)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho **'20'**, **deve** ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

Qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)

Sabendo

{tamanho, podedeve}

e usando

Eq(tamanho, justificação)

determina-se

{justificação}

Sabendo

{tamanho, podedeve, justificação}

e usando

Eq(tamanho, corrigido + justificação)

determina-se

{corrigido}




## variante 06 (excel row is 05)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho **'100'**, {:MULTICHOICE_S:%0%deve\~%100%pode} ser usado o desvio padrão {:MULTICHOICE_S:%0%corrigido\~%100%corrigido ou não} 
pois o desvio padrão corrigido é **aproximado ao** desvio padrão não corrigido.

Qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)

Sabendo

{tamanho, justificação}

e usando

Eq(tamanho, corrigido + justificação)

determina-se

{corrigido}

Sabendo

{tamanho, corrigido, justificação}

e usando

Eq(tamanho, corrigido + podedeve)

determina-se

{podedeve}




## variante 07 (excel row is 06)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho **'1000'**, {:MULTICHOICE_S:%0%deve\~%100%pode} ser usado o desvio padrão {:MULTICHOICE_S:%0%corrigido\~%100%corrigido ou não} 
pois o desvio padrão corrigido é **aproximado ao** desvio padrão não corrigido.

Qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)

Sabendo

{tamanho, justificação}

e usando

Eq(tamanho, corrigido + justificação)

determina-se

{corrigido}

Sabendo

{tamanho, corrigido, justificação}

e usando

Eq(tamanho, corrigido + podedeve)

determina-se

{podedeve}




## variante 08 (excel row is 01)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), **deve** ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

Qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)

Sabendo

{corrigido, podedeve}

e usando

Eq(tamanho, corrigido + justificação)

Eq(tamanho, justificação)

determina-se

{tamanho, justificação}




## variante 09 (excel row is 02)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), **deve** ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

Qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)

Sabendo

{corrigido, podedeve}

e usando

Eq(tamanho, corrigido + justificação)

Eq(tamanho, justificação)

determina-se

{tamanho, justificação}




## variante 10 (excel row is 03)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.

Qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)

Sabendo

{corrigido, justificação}

e usando

Eq(tamanho, corrigido + justificação)

determina-se

{tamanho}

Sabendo

{tamanho, corrigido, justificação}

e usando

Eq(tamanho, corrigido + podedeve)

determina-se

{podedeve}




## variante 11 (excel row is 04)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.

Qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)

Sabendo

{corrigido, justificação}

e usando

Eq(tamanho, corrigido + justificação)

determina-se

{tamanho}

Sabendo

{tamanho, corrigido, justificação}

e usando

Eq(tamanho, corrigido + podedeve)

determina-se

{podedeve}




## variante 12 (excel row is 05)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%0%'2'\~%0%'4'\~%0%'10'\~%0%'20'\~%100%'100'\~%100%'1000'} (indique uma de várias soluções), **pode** ser usado o desvio padrão {:MULTICHOICE_S:%0%corrigido\~%100%corrigido ou não} 
pois o desvio padrão corrigido é **aproximado ao** desvio padrão não corrigido.

Qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)

Sabendo

{podedeve, justificação}

e usando

Eq(tamanho, corrigido + justificação)

Eq(tamanho, corrigido + podedeve)

determina-se

{tamanho, corrigido}




## variante 13 (excel row is 06)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%0%'2'\~%0%'4'\~%0%'10'\~%0%'20'\~%100%'100'\~%100%'1000'} (indique uma de várias soluções), **pode** ser usado o desvio padrão {:MULTICHOICE_S:%0%corrigido\~%100%corrigido ou não} 
pois o desvio padrão corrigido é **aproximado ao** desvio padrão não corrigido.

Qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)

Sabendo

{podedeve, justificação}

e usando

Eq(tamanho, corrigido + justificação)

Eq(tamanho, corrigido + podedeve)

determina-se

{tamanho, corrigido}




## variante 02 (excel row is 01)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho **'2'**, {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

Qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)

Sabendo

{tamanho}

e usando

Eq(tamanho, justificação)

determina-se

{justificação}

Sabendo

{tamanho, justificação}

e usando

Eq(tamanho, corrigido + justificação)

determina-se

{corrigido}

Sabendo

{tamanho, corrigido, justificação}

e usando

Eq(tamanho, corrigido + podedeve)

determina-se

{podedeve}




## variante 03 (excel row is 02)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho **'4'**, {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

Qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)

Sabendo

{tamanho}

e usando

Eq(tamanho, justificação)

determina-se

{justificação}

Sabendo

{tamanho, justificação}

e usando

Eq(tamanho, corrigido + justificação)

determina-se

{corrigido}

Sabendo

{tamanho, corrigido, justificação}

e usando

Eq(tamanho, corrigido + podedeve)

determina-se

{podedeve}




## variante 04 (excel row is 03)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

Qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)

Sabendo

{corrigido}

e usando

Eq(tamanho, corrigido + justificação)

Eq(tamanho, justificação)

determina-se

{tamanho, justificação}

Sabendo

{tamanho, corrigido, justificação}

e usando

Eq(tamanho, corrigido + podedeve)

determina-se

{podedeve}




## variante 05 (excel row is 04)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão **corrigido** 
pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

Qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)

Sabendo

{corrigido}

e usando

Eq(tamanho, corrigido + justificação)

Eq(tamanho, justificação)

determina-se

{tamanho, justificação}

Sabendo

{tamanho, corrigido, justificação}

e usando

Eq(tamanho, corrigido + podedeve)

determina-se

{podedeve}




## variante 06 (excel row is 05)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%0%'2'\~%0%'4'\~%0%'10'\~%0%'20'\~%100%'100'\~%100%'1000'} (indique uma de várias soluções), {:MULTICHOICE_S:%0%deve\~%100%pode} ser usado o desvio padrão {:MULTICHOICE_S:%0%corrigido\~%100%corrigido ou não} 
pois o desvio padrão corrigido é **aproximado ao** desvio padrão não corrigido.

Qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)

Sabendo

{justificação}

e usando

Eq(tamanho, justificação)

determina-se

{tamanho}

Sabendo

{tamanho, justificação}

e usando

Eq(tamanho, corrigido + justificação)

determina-se

{corrigido}

Sabendo

{tamanho, corrigido, justificação}

e usando

Eq(tamanho, corrigido + podedeve)

determina-se

{podedeve}




## variante 07 (excel row is 06)

O desvio padrão corrigido é um estimador centrado para o desvio padrão do modelo populacional \(\sigma^2\).

**(a)** Justifique que \(s_c^2\) é estritamente maior que \(s^2\) mas nem sempre "muito maior".

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%0%'2'\~%0%'4'\~%0%'10'\~%0%'20'\~%100%'100'\~%100%'1000'} (indique uma de várias soluções), {:MULTICHOICE_S:%0%deve\~%100%pode} ser usado o desvio padrão {:MULTICHOICE_S:%0%corrigido\~%100%corrigido ou não} 
pois o desvio padrão corrigido é **aproximado ao** desvio padrão não corrigido.

Qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)

Sabendo

{justificação}

e usando

Eq(tamanho, justificação)

determina-se

{tamanho}

Sabendo

{tamanho, justificação}

e usando

Eq(tamanho, corrigido + justificação)

determina-se

{corrigido}

Sabendo

{tamanho, corrigido, justificação}

e usando

Eq(tamanho, corrigido + podedeve)

determina-se

{podedeve}



