
---
title: "sc_or_s-study.Rmd"
author: "Pedro Cruz"
date: "2025-01-27_17-38-48"
output:
  html_document: default
---


# Model sc_or_s-study.Rmd - CLOZE



## variante 001 (data row is 01)


## variante 001 (data row is 01)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%0%'4'\~%0%'10'\~%0%'20'\~%0%'100'\~%0%'1000'} a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = **1.414** \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%0%'4'\~%0%'10'\~%0%'20'\~%0%'100'\~%0%'1000'}, **deve** ser usado o desvio padrão **corrigido** pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None


## variante 002 (data row is 02)


## variante 002 (data row is 02)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho **'4'** a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = **1.155** \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho **'4'**, **deve** ser usado o desvio padrão **corrigido** pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None


## variante 003 (data row is 03)


## variante 003 (data row is 03)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho **'10'** a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = **1.054** \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho **'10'**, **deve** ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None


## variante 004 (data row is 04)


## variante 004 (data row is 04)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho **'20'** a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = {:NUMERICAL:%100%1.026:0.01} \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho **'20'**, **deve** ser usado o desvio padrão **corrigido** pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None


## variante 005 (data row is 05)


## variante 005 (data row is 05)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho **'100'** a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = **1.005** \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho **'100'**, {:MULTICHOICE_S:%0%deve\~%100%pode} ser usado o desvio padrão **corrigido ou não** pois o desvio padrão corrigido é **aproximado ao** desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None


## variante 006 (data row is 06)


## variante 006 (data row is 06)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho {:MULTICHOICE_S:%0%'2'\~%0%'4'\~%0%'10'\~%0%'20'\~%0%'100'\~%100%'1000'} a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = **1.001** \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%0%'2'\~%0%'4'\~%0%'10'\~%0%'20'\~%0%'100'\~%100%'1000'}, **pode** ser usado o desvio padrão **corrigido ou não** pois o desvio padrão corrigido é {:MULTICHOICE_S:%0%maior, ou bastante maior, que o\~%100%aproximado ao} desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None


## variante 007 (data row is 01)


## variante 007 (data row is 01)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%0%'4'\~%0%'10'\~%0%'20'\~%0%'100'\~%0%'1000'} a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = **1.414** \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%0%'4'\~%0%'10'\~%0%'20'\~%0%'100'\~%0%'1000'}, **deve** ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None


## variante 008 (data row is 02)


## variante 008 (data row is 02)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho **'4'** a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = **1.155** \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho **'4'**, **deve** ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None


## variante 009 (data row is 03)


## variante 009 (data row is 03)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções) a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = {:NUMERICAL:%100%1.414:0.01\~%100%1.155:0.01\~%100%1.054:0.01\~%100%1.026:0.01} (indique uma de várias soluções) \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), **deve** ser usado o desvio padrão **corrigido** pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None


## variante 010 (data row is 04)


## variante 010 (data row is 04)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho **'20'** a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = {:NUMERICAL:%100%1.026:0.01} \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho **'20'**, **deve** ser usado o desvio padrão **corrigido** pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None


## variante 011 (data row is 05)


## variante 011 (data row is 05)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho **'100'** a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = {:NUMERICAL:%100%1.005:0.01} \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho **'100'**, **pode** ser usado o desvio padrão {:MULTICHOICE_S:%0%corrigido\~%100%corrigido ou não} pois o desvio padrão corrigido é **aproximado ao** desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None


## variante 012 (data row is 06)


## variante 012 (data row is 06)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho {:MULTICHOICE_S:%0%'2'\~%0%'4'\~%0%'10'\~%0%'20'\~%0%'100'\~%100%'1000'} a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = **1.001** \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%0%'2'\~%0%'4'\~%0%'10'\~%0%'20'\~%0%'100'\~%100%'1000'}, {:MULTICHOICE_S:%0%deve\~%100%pode} ser usado o desvio padrão **corrigido ou não** pois o desvio padrão corrigido é **aproximado ao** desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None


## variante 013 (data row is 01)


## variante 013 (data row is 01)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho **'2'** a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = **1.414** \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho **'2'**, {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão **corrigido** pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None


## variante 014 (data row is 02)


## variante 014 (data row is 02)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho **'4'** a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = **1.155** \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho **'4'**, {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None


## variante 015 (data row is 03)


## variante 015 (data row is 03)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho **'10'** a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = {:NUMERICAL:%100%1.054:0.01} \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho **'10'**, {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão **corrigido** pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None


## variante 016 (data row is 04)


## variante 016 (data row is 04)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho {:MULTICHOICE_S:%0%'2'\~%0%'4'\~%0%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = **1.026** \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%0%'2'\~%0%'4'\~%0%'10'\~%100%'20'\~%0%'100'\~%0%'1000'}, **deve** ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None


## variante 017 (data row is 05)


## variante 017 (data row is 05)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho {:MULTICHOICE_S:%0%'2'\~%0%'4'\~%0%'10'\~%0%'20'\~%100%'100'\~%100%'1000'} (indique uma de várias soluções) a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = {:NUMERICAL:%100%1.005:0.01\~%100%1.001:0.01} (indique uma de várias soluções) \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%0%'2'\~%0%'4'\~%0%'10'\~%0%'20'\~%100%'100'\~%100%'1000'} (indique uma de várias soluções), **pode** ser usado o desvio padrão {:MULTICHOICE_S:%0%corrigido\~%100%corrigido ou não} pois o desvio padrão corrigido é **aproximado ao** desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None


## variante 018 (data row is 06)


## variante 018 (data row is 06)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho **'1000'** a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = {:NUMERICAL:%100%1.001:0.01} \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho **'1000'**, **pode** ser usado o desvio padrão {:MULTICHOICE_S:%0%corrigido\~%100%corrigido ou não} pois o desvio padrão corrigido é {:MULTICHOICE_S:%0%maior, ou bastante maior, que o\~%100%aproximado ao} desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None


## variante 019 (data row is 01)


## variante 019 (data row is 01)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%0%'4'\~%0%'10'\~%0%'20'\~%0%'100'\~%0%'1000'} a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = **1.414** \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%0%'4'\~%0%'10'\~%0%'20'\~%0%'100'\~%0%'1000'}, {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão **corrigido** pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None


## variante 020 (data row is 02)


## variante 020 (data row is 02)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho {:MULTICHOICE_S:%0%'2'\~%100%'4'\~%0%'10'\~%0%'20'\~%0%'100'\~%0%'1000'} a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = **1.155** \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%0%'2'\~%100%'4'\~%0%'10'\~%0%'20'\~%0%'100'\~%0%'1000'}, {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None


## variante 021 (data row is 03)


## variante 021 (data row is 03)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho **'10'** a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = **1.054** \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho **'10'**, {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None


## variante 022 (data row is 04)


## variante 022 (data row is 04)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções) a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = {:NUMERICAL:%100%1.414:0.01\~%100%1.155:0.01\~%100%1.054:0.01\~%100%1.026:0.01} (indique uma de várias soluções) \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão **corrigido** pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None


## variante 023 (data row is 05)


## variante 023 (data row is 05)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho **'100'** a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = {:NUMERICAL:%100%1.005:0.01} \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho **'100'**, {:MULTICHOICE_S:%0%deve\~%100%pode} ser usado o desvio padrão **corrigido ou não** pois o desvio padrão corrigido é {:MULTICHOICE_S:%0%maior, ou bastante maior, que o\~%100%aproximado ao} desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None


## variante 024 (data row is 06)


## variante 024 (data row is 06)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho **'1000'** a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = {:NUMERICAL:%100%1.001:0.01} \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho **'1000'**, {:MULTICHOICE_S:%0%deve\~%100%pode} ser usado o desvio padrão {:MULTICHOICE_S:%0%corrigido\~%100%corrigido ou não} pois o desvio padrão corrigido é **aproximado ao** desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None


## variante 025 (data row is 01)


## variante 025 (data row is 01)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%0%'4'\~%0%'10'\~%0%'20'\~%0%'100'\~%0%'1000'} a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = **1.414** \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%0%'4'\~%0%'10'\~%0%'20'\~%0%'100'\~%0%'1000'}, {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None


## variante 026 (data row is 02)


## variante 026 (data row is 02)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções) a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = {:NUMERICAL:%100%1.414:0.01\~%100%1.155:0.01\~%100%1.054:0.01\~%100%1.026:0.01} (indique uma de várias soluções) \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho {:MULTICHOICE_S:%100%'2'\~%100%'4'\~%100%'10'\~%100%'20'\~%0%'100'\~%0%'1000'} (indique uma de várias soluções), {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} pois o desvio padrão corrigido é **maior, ou bastante maior, que o** desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None


## variante 027 (data row is 03)


## variante 027 (data row is 03)

O desvio padrão corrigido, \(s_c\), é um estimador centrado para o desvio padrão do modelo populacional \(\sigma\), 
\(E[s_c] = \sigma\).

**(a)** Verifique que para uma amostra de tamanho **'10'** a relação entre \(s_c\) e \(s\) é dada por:

* \(s_c\) = {:NUMERICAL:%100%1.054:0.01} \(s\)

Apenas para efeitos da próxima alínea, considere, agora, que um racio \(s_c/s\) inferior a 1.01 é negligenciável.

**(b)** Com uma amostra de tamanho **'10'**, {:MULTICHOICE_S:%100%deve\~%0%pode} ser usado o desvio padrão {:MULTICHOICE_S:%100%corrigido\~%0%corrigido ou não} pois o desvio padrão corrigido é {:MULTICHOICE_S:%100%maior, ou bastante maior, que o\~%0%aproximado ao} desvio padrão não corrigido.

Avalie a qualidade deste exercício para o estudo: {:MULTICHOICE:=útil\~%100%não útil\~%100%não compreendo\~%100%acho que não tem solução}.


### feedback

(Consulte o docente das suas turmas ou uma OT.)


### feedback

None
