---
title: "dados-study.Rmd"
author: "Pedro Cruz"
date: "2025-02-20_15-22-26"
output:
  html_document: default
---


# Model dados-study.Rmd - CLOZE



## variante 001 (data row is 01)


Considere um teste de hipóteses 
unilateral à direita para a média \(\mu\) de uma dada população Normal com variância conhecida.


H0: \(\mu = 5\) versus  H1: \(\mu > 5\)

Considerando:

* \(z_obs\) = **3.0902**
* valor-p = **0.001** = \( P(Z \le  z_obs) \)
* \(\alpha\) = **0.01**

a conclusão

**Rejeita-se** a hipótese nula (H0) porque \(\alpha\) **é maior** que valor-p.

### feedback



#(Consulte o docente das suas turmas ou uma OT.)




## variante 002 (data row is 02)


Considere um teste de hipóteses 
unilateral à direita para a média \(\mu\) de uma dada população Normal com variância conhecida.


H0: \(\mu = 5\) versus  H1: \(\mu > 5\)

Considerando:

* \(z_obs\) = **1.6449**
* valor-p = **0.05** = \( P(Z \le  z_obs) \)
* \(\alpha\) = **0.01**

a conclusão

**Não se rejeita** a hipótese nula (H0) porque \(\alpha\) {:MULTICHOICE_S:%0%é maior\~%100%é menor} que valor-p.

### feedback



#(Consulte o docente das suas turmas ou uma OT.)




## variante 003 (data row is 03)


Considere um teste de hipóteses 
unilateral à direita para a média \(\mu\) de uma dada população Normal com variância conhecida.


H0: \(\mu = 5\) versus  H1: \(\mu > 5\)

Considerando:

* \(z_obs\) = **2.3263**
* valor-p = **0.01** = \( P(Z \le  z_obs) \)
* \(\alpha\) = **0.05**

a conclusão

{:MULTICHOICE_S:%100%Rejeita-se\~%0%Não se rejeita} a hipótese nula (H0) porque \(\alpha\) {:MULTICHOICE_S:%100%é maior\~%0%é menor} que valor-p.

### feedback



#(Consulte o docente das suas turmas ou uma OT.)




## variante 004 (data row is 04)


Considere um teste de hipóteses 
unilateral à direita para a média \(\mu\) de uma dada população Normal com variância conhecida.


H0: \(\mu = 5\) versus  H1: \(\mu > 5\)

Considerando:

* \(z_obs\) = **0.5244**
* valor-p = {:NUMERICAL:%100%0.3:0.01} = \( P(Z \le  z_obs) \)
* \(\alpha\) = **0.05**

a conclusão

{:MULTICHOICE_S:%0%Rejeita-se\~%100%Não se rejeita} a hipótese nula (H0) porque \(\alpha\) {:MULTICHOICE_S:%0%é maior\~%100%é menor} que valor-p.

### feedback



#(Consulte o docente das suas turmas ou uma OT.)


