---
title: "dados-study.Rmd"
author: "Pedro Cruz"
date: "2025-02-20_15-26-18"
output:
  html_document: default
---


# Model dados-study.Rmd - CLOZE



## variante 001 (data row is 01)


Considere um teste de hipóteses 
unilateral à direita para a média \(\mu\) de uma dada população Normal com variância conhecida.


H0: \(\mu = 5\) versus  H1: \(\mu > 5\)

Considerando

* \(z_\text{obs}\) = **3.0902**,
* valor-p = **0.001** = \( P(Z \ge  z_\text{obs}) \),
* \(\alpha\) = **0.01**

segue a conclusão é que

* **rejeita-se** a hipótese nula (H0) porque \(\alpha\) {:MULTICHOICE_S:%100%é maior\~%0%é menor} que o valor-p.

Assim, a média populacional (ou valor esperado) \(\mu\) **não é significativamente maior** que 5.
### feedback



#(Consulte o docente das suas turmas ou uma OT.)




## variante 002 (data row is 02)


Considere um teste de hipóteses 
unilateral à direita para a média \(\mu\) de uma dada população Normal com variância conhecida.


H0: \(\mu = 5\) versus  H1: \(\mu > 5\)

Considerando

* \(z_\text{obs}\) = **1.6449**,
* valor-p = **0.05** = \( P(Z \ge  z_\text{obs}) \),
* \(\alpha\) = **0.01**

segue a conclusão é que

* **não se rejeita** a hipótese nula (H0) porque \(\alpha\) {:MULTICHOICE_S:%0%é maior\~%100%é menor} que o valor-p.

Assim, a média populacional (ou valor esperado) \(\mu\) {:MULTICHOICE_S:%0%não é significativamente maior\~%100%é significativamente maior} que 5.
### feedback



#(Consulte o docente das suas turmas ou uma OT.)




## variante 003 (data row is 03)


Considere um teste de hipóteses 
unilateral à direita para a média \(\mu\) de uma dada população Normal com variância conhecida.


H0: \(\mu = 5\) versus  H1: \(\mu > 5\)

Considerando

* \(z_\text{obs}\) = **2.3263**,
* valor-p = **0.01** = \( P(Z \ge  z_\text{obs}) \),
* \(\alpha\) = **0.05**

segue a conclusão é que

* {:MULTICHOICE_S:%100%rejeita-se\~%0%não se rejeita} a hipótese nula (H0) porque \(\alpha\) {:MULTICHOICE_S:%100%é maior\~%0%é menor} que o valor-p.

Assim, a média populacional (ou valor esperado) \(\mu\) {:MULTICHOICE_S:%100%não é significativamente maior\~%0%é significativamente maior} que 5.

### feedback



(Consulte o docente das suas turmas ou uma OT.)




## variante 004 (data row is 04)


Considere um teste de hipóteses 
unilateral à direita para a média \(\mu\) de uma dada população Normal com variância conhecida.


H0: \(\mu = 5\) versus  H1: \(\mu > 5\)

Considerando

* \(z_\text{obs}\) = {:NUMERICAL:%100%0.5244:0.01},
* valor-p = **0.3** = \( P(Z \ge  z_\text{obs}) \),
* \(\alpha\) = **0.05**

segue a conclusão é que

* {:MULTICHOICE_S:%0%rejeita-se\~%100%não se rejeita} a hipótese nula (H0) porque \(\alpha\) {:MULTICHOICE_S:%0%é maior\~%100%é menor} que o valor-p.

Assim, a média populacional (ou valor esperado) \(\mu\) {:MULTICHOICE_S:%0%não é significativamente maior\~%100%é significativamente maior} que 5.
### feedback



#(Consulte o docente das suas turmas ou uma OT.)


