# pyequa defaults


answer_template: |
  Knowing

  {localgivenvars}

  and using

  {solvers}

  it can be found

  {localrequestedvars}




# 
student_feedback: |
  
  (No feedback is available. Please consult your class teacher(s).)



# Output destination of the produced exercises
output_service: moodle_cloze
output_extension: md #output to a markdown file


# In a folder, the standard filename for anexercise template
student_template_filename: exercise_model.md

# CSV as a standard format
dataframe_type: csv # xlsx  or csv 
csv_separator: "," 
csv_decimal: "." 


author: Pedro Cruz


# challenge vs exam
gen_method: exam

# when gen_method is 'challenge'
# number of variants of the same exercise model
number_of_variants_per_exercise: 1 

# when gen_method is 'fixed' 
number_of_given_vars: 1
#TODO: "only input vars" 


# when gen_method is 'all'
# TODO

several_solutions: " (mais que uma solução; escolha uma) "

# output a knowledge graph
output_knowledge_graph: true






