---
title: "dados-study.Rmd"
author: "Pedro Cruz"
date: "2025-01-31_18-57-29"
output:
  html_document: default
---


# Model dados-study.Rmd - CLOZE



## variante 001 (data row is 01)

A probabilidade de acerto no alvo é p=**0.6**.

A variável aleatória

X = "número de acertos no tiro ao alvo em n=**30** tiros"

é modelada por uma distribuição Binomial(n,p). 

Então,

P(X menor ou igual a **20** | \(X \sim \text{Binomial}\)) = **0.8237135152559875**.

O conceito seguinte têm aplicação no Capítulo 3.

Uma Binomial é uma soma de variáveis 0 ou 1 (contagem de sucessos). Então, usando o TLC, uma distribuição Binomial(n,p) aproxima-se a uma distribuição Normal com os seguintes parâmetros: Normal(np, np(1-p)):

* a média da Normal é E[X] = np = {:NUMERICAL:%100%18.0:0.01}
* variância da Normal é Var[X] = np(1-p) = **7.2**

Usando esta distribuição aproximada,

P(X menor ou igual a **20** | \(X \sim_\text{aprox.} \text{Normal}\)) = {:NUMERICAL:%100%0.7719717298748721:0.01}.

Costuma-se usar a seguintes regras que sugerem que a probabilidades calculadas pela Binomial e pela Normal são próximas:

* média da Binomial = \(np \ge 5\) que {:MULTICHOICE_S:%100%se verifica\~%0%não se verifica}, e,
* variância da Binomial = \(np(1-p) \ge 5\) que {:MULTICHOICE_S:%100%se verifica\~%0%não se verifica},
* \(n \ge 30 \) que {:MULTICHOICE_S:%100%se verifica\~%0%não se verifica} (regra usual do TLC),



### feedback



#(Consulte o docente das suas turmas ou uma OT.)


