---
title: "dados-study.Rmd"
author: "Pedro Cruz"
date: "2025-01-31_18-58-07"
output:
  html_document: default
---


# Model dados-study.Rmd - CLOZE



## variante 001 (data row is 01)

A probabilidade de acerto no alvo é p=**0.6**.

A variável aleatória

X = "número de acertos no tiro ao alvo em n=**30** tiros"

é modelada por uma distribuição Binomial(n,p). 

Então,

P(X menor ou igual a **20** | \(X \sim \text{Binomial}\)) = **0.8237135152559875**.

O conceito seguinte têm aplicação no Capítulo 3.

Uma Binomial é uma soma de variáveis 0 ou 1 (contagem de sucessos). Então, usando o TLC, uma distribuição Binomial(n,p) aproxima-se a uma distribuição Normal com os seguintes parâmetros: Normal(np, np(1-p)):

* a média da Normal é E[X] = np = {:NUMERICAL:%100%18.0:0.01}
* variância da Normal é Var[X] = np(1-p) = {:NUMERICAL:%100%7.2:0.01}

Usando esta distribuição aproximada,

P(X menor ou igual a **20** | \(X \sim_\text{aprox.} \text{Normal}\)) = {:NUMERICAL:%100%0.7719717298748721:0.01}.

Costuma-se usar a seguintes regras que sugerem que a probabilidades calculadas pela Binomial e pela Normal são próximas:

* média da Binomial = \(np \ge 5\) que {:MULTICHOICE_S:%100%se verifica\~%0%não se verifica}, e,
* variância da Binomial = \(np(1-p) \ge 5\) que {:MULTICHOICE_S:%100%se verifica\~%0%não se verifica},
* \(n \ge 30 \) que {:MULTICHOICE_S:%100%se verifica\~%0%não se verifica} (regra usual do TLC),



### feedback



#(Consulte o docente das suas turmas ou uma OT.)




## variante 002 (data row is 02)

A probabilidade de acerto no alvo é p=**0.6**.

A variável aleatória

X = "número de acertos no tiro ao alvo em n=**20** tiros"

é modelada por uma distribuição Binomial(n,p). 

Então,

P(X menor ou igual a **14** | \(X \sim \text{Binomial}\)) = {:NUMERICAL:%100%0.8744010272769627:0.01}.

O conceito seguinte têm aplicação no Capítulo 3.

Uma Binomial é uma soma de variáveis 0 ou 1 (contagem de sucessos). Então, usando o TLC, uma distribuição Binomial(n,p) aproxima-se a uma distribuição Normal com os seguintes parâmetros: Normal(np, np(1-p)):

* a média da Normal é E[X] = np = **12.0**
* variância da Normal é Var[X] = np(1-p) = {:NUMERICAL:%100%4.800000000000001:0.01}

Usando esta distribuição aproximada,

P(X menor ou igual a **14** | \(X \sim_\text{aprox.} \text{Normal}\)) = {:NUMERICAL:%100%0.8193447857369106:0.01}.

Costuma-se usar a seguintes regras que sugerem que a probabilidades calculadas pela Binomial e pela Normal são próximas:

* média da Binomial = \(np \ge 5\) que {:MULTICHOICE_S:%100%se verifica\~%0%não se verifica}, e,
* variância da Binomial = \(np(1-p) \ge 5\) que {:MULTICHOICE_S:%0%se verifica\~%100%não se verifica},
* \(n \ge 30 \) que {:MULTICHOICE_S:%0%se verifica\~%100%não se verifica} (regra usual do TLC),



### feedback



#(Consulte o docente das suas turmas ou uma OT.)




## variante 003 (data row is 03)

A probabilidade de acerto no alvo é p=**0.2**.

A variável aleatória

X = "número de acertos no tiro ao alvo em n=**10** tiros"

é modelada por uma distribuição Binomial(n,p). 

Então,

P(X menor ou igual a **3** | \(X \sim \text{Binomial}\)) = {:NUMERICAL:%100%0.8791261184:0.01}.

O conceito seguinte têm aplicação no Capítulo 3.

Uma Binomial é uma soma de variáveis 0 ou 1 (contagem de sucessos). Então, usando o TLC, uma distribuição Binomial(n,p) aproxima-se a uma distribuição Normal com os seguintes parâmetros: Normal(np, np(1-p)):

* a média da Normal é E[X] = np = {:NUMERICAL:%100%2.0:0.01}
* variância da Normal é Var[X] = np(1-p) = **1.6**

Usando esta distribuição aproximada,

P(X menor ou igual a **3** | \(X \sim_\text{aprox.} \text{Normal}\)) = {:NUMERICAL:%100%0.7854023497798255:0.01}.

Costuma-se usar a seguintes regras que sugerem que a probabilidades calculadas pela Binomial e pela Normal são próximas:

* média da Binomial = \(np \ge 5\) que {:MULTICHOICE_S:%0%se verifica\~%100%não se verifica}, e,
* variância da Binomial = \(np(1-p) \ge 5\) que {:MULTICHOICE_S:%0%se verifica\~%100%não se verifica},
* \(n \ge 30 \) que {:MULTICHOICE_S:%0%se verifica\~%100%não se verifica} (regra usual do TLC),



### feedback



#(Consulte o docente das suas turmas ou uma OT.)




## variante 004 (data row is 04)

A probabilidade de acerto no alvo é p=**0.3**.

A variável aleatória

X = "número de acertos no tiro ao alvo em n=**10** tiros"

é modelada por uma distribuição Binomial(n,p). 

Então,

P(X menor ou igual a **4** | \(X \sim \text{Binomial}\)) = {:NUMERICAL:%100%0.8497316674:0.01}.

O conceito seguinte têm aplicação no Capítulo 3.

Uma Binomial é uma soma de variáveis 0 ou 1 (contagem de sucessos). Então, usando o TLC, uma distribuição Binomial(n,p) aproxima-se a uma distribuição Normal com os seguintes parâmetros: Normal(np, np(1-p)):

* a média da Normal é E[X] = np = {:NUMERICAL:%100%3.0:0.01}
* variância da Normal é Var[X] = np(1-p) = {:NUMERICAL:%100%2.0999999999999996:0.01}

Usando esta distribuição aproximada,

P(X menor ou igual a **4** | \(X \sim_\text{aprox.} \text{Normal}\)) = {:NUMERICAL:%100%0.7549235197920876:0.01}.

Costuma-se usar a seguintes regras que sugerem que a probabilidades calculadas pela Binomial e pela Normal são próximas:

* média da Binomial = \(np \ge 5\) que {:MULTICHOICE_S:%0%se verifica\~%100%não se verifica}, e,
* variância da Binomial = \(np(1-p) \ge 5\) que {:MULTICHOICE_S:%0%se verifica\~%100%não se verifica},
* \(n \ge 30 \) que **não se verifica** (regra usual do TLC),



### feedback



#(Consulte o docente das suas turmas ou uma OT.)




## variante 005 (data row is 05)

A probabilidade de acerto no alvo é p=**0.7**.

A variável aleatória

X = "número de acertos no tiro ao alvo em n=**10** tiros"

é modelada por uma distribuição Binomial(n,p). 

Então,

P(X menor ou igual a **8** | \(X \sim \text{Binomial}\)) = {:NUMERICAL:%100%0.8506916541:0.01}.

O conceito seguinte têm aplicação no Capítulo 3.

Uma Binomial é uma soma de variáveis 0 ou 1 (contagem de sucessos). Então, usando o TLC, uma distribuição Binomial(n,p) aproxima-se a uma distribuição Normal com os seguintes parâmetros: Normal(np, np(1-p)):

* a média da Normal é E[X] = np = {:NUMERICAL:%100%7.0:0.01}
* variância da Normal é Var[X] = np(1-p) = {:NUMERICAL:%100%2.1000000000000005:0.01}

Usando esta distribuição aproximada,

P(X menor ou igual a **8** | \(X \sim_\text{aprox.} \text{Normal}\)) = **0.7549235197920875**.

Costuma-se usar a seguintes regras que sugerem que a probabilidades calculadas pela Binomial e pela Normal são próximas:

* média da Binomial = \(np \ge 5\) que {:MULTICHOICE_S:%100%se verifica\~%0%não se verifica}, e,
* variância da Binomial = \(np(1-p) \ge 5\) que {:MULTICHOICE_S:%0%se verifica\~%100%não se verifica},
* \(n \ge 30 \) que {:MULTICHOICE_S:%0%se verifica\~%100%não se verifica} (regra usual do TLC),



### feedback



#(Consulte o docente das suas turmas ou uma OT.)




## variante 006 (data row is 06)

A probabilidade de acerto no alvo é p=**0.3**.

A variável aleatória

X = "número de acertos no tiro ao alvo em n={:NUMERICAL:%100%25:0.01} tiros"

é modelada por uma distribuição Binomial(n,p). 

Então,

P(X menor ou igual a **5** | \(X \sim \text{Binomial}\)) = **0.19348844208806504**.

O conceito seguinte têm aplicação no Capítulo 3.

Uma Binomial é uma soma de variáveis 0 ou 1 (contagem de sucessos). Então, usando o TLC, uma distribuição Binomial(n,p) aproxima-se a uma distribuição Normal com os seguintes parâmetros: Normal(np, np(1-p)):

* a média da Normal é E[X] = np = **7.5**
* variância da Normal é Var[X] = np(1-p) = {:NUMERICAL:%100%5.25:0.01}

Usando esta distribuição aproximada,

P(X menor ou igual a **5** | \(X \sim_\text{aprox.} \text{Normal}\)) = {:NUMERICAL:%100%0.13761676203741716:0.01}.

Costuma-se usar a seguintes regras que sugerem que a probabilidades calculadas pela Binomial e pela Normal são próximas:

* média da Binomial = \(np \ge 5\) que {:MULTICHOICE_S:%100%se verifica\~%0%não se verifica}, e,
* variância da Binomial = \(np(1-p) \ge 5\) que {:MULTICHOICE_S:%100%se verifica\~%0%não se verifica},
* \(n \ge 30 \) que {:MULTICHOICE_S:%0%se verifica\~%100%não se verifica} (regra usual do TLC),



### feedback



#(Consulte o docente das suas turmas ou uma OT.)




## variante 007 (data row is 07)

A probabilidade de acerto no alvo é p=**0.4**.

A variável aleatória

X = "número de acertos no tiro ao alvo em n={:NUMERICAL:%100%20:0.01} tiros"

é modelada por uma distribuição Binomial(n,p). 

Então,

P(X menor ou igual a **5** | \(X \sim \text{Binomial}\)) = **0.12559897272303736**.

O conceito seguinte têm aplicação no Capítulo 3.

Uma Binomial é uma soma de variáveis 0 ou 1 (contagem de sucessos). Então, usando o TLC, uma distribuição Binomial(n,p) aproxima-se a uma distribuição Normal com os seguintes parâmetros: Normal(np, np(1-p)):

* a média da Normal é E[X] = np = {:NUMERICAL:%100%8.0:0.01}
* variância da Normal é Var[X] = np(1-p) = **4.8**

Usando esta distribuição aproximada,

P(X menor ou igual a **5** | \(X \sim_\text{aprox.} \text{Normal}\)) = {:NUMERICAL:%100%0.08545176011539872:0.01}.

Costuma-se usar a seguintes regras que sugerem que a probabilidades calculadas pela Binomial e pela Normal são próximas:

* média da Binomial = \(np \ge 5\) que {:MULTICHOICE_S:%100%se verifica\~%0%não se verifica}, e,
* variância da Binomial = \(np(1-p) \ge 5\) que {:MULTICHOICE_S:%0%se verifica\~%100%não se verifica},
* \(n \ge 30 \) que {:MULTICHOICE_S:%0%se verifica\~%100%não se verifica} (regra usual do TLC),



### feedback



#(Consulte o docente das suas turmas ou uma OT.)




## variante 008 (data row is 08)

A probabilidade de acerto no alvo é p={:NUMERICAL:%100%0.3:0.01}.

A variável aleatória

X = "número de acertos no tiro ao alvo em n=**30** tiros"

é modelada por uma distribuição Binomial(n,p). 

Então,

P(X menor ou igual a **10** | \(X \sim \text{Binomial}\)) = **0.7303703863027229**.

O conceito seguinte têm aplicação no Capítulo 3.

Uma Binomial é uma soma de variáveis 0 ou 1 (contagem de sucessos). Então, usando o TLC, uma distribuição Binomial(n,p) aproxima-se a uma distribuição Normal com os seguintes parâmetros: Normal(np, np(1-p)):

* a média da Normal é E[X] = np = **9.0**
* variância da Normal é Var[X] = np(1-p) = {:NUMERICAL:%100%6.3:0.01}

Usando esta distribuição aproximada,

P(X menor ou igual a **10** | \(X \sim_\text{aprox.} \text{Normal}\)) = {:NUMERICAL:%100%0.6548358352679033:0.01}.

Costuma-se usar a seguintes regras que sugerem que a probabilidades calculadas pela Binomial e pela Normal são próximas:

* média da Binomial = \(np \ge 5\) que {:MULTICHOICE_S:%100%se verifica\~%0%não se verifica}, e,
* variância da Binomial = \(np(1-p) \ge 5\) que {:MULTICHOICE_S:%100%se verifica\~%0%não se verifica},
* \(n \ge 30 \) que {:MULTICHOICE_S:%100%se verifica\~%0%não se verifica} (regra usual do TLC),



### feedback



#(Consulte o docente das suas turmas ou uma OT.)




## variante 009 (data row is 01)

A probabilidade de acerto no alvo é p={:NUMERICAL:%100%0.6:0.01}.

A variável aleatória

X = "número de acertos no tiro ao alvo em n=**30** tiros"

é modelada por uma distribuição Binomial(n,p). 

Então,

P(X menor ou igual a **20** | \(X \sim \text{Binomial}\)) = **0.8237135152559875**.

O conceito seguinte têm aplicação no Capítulo 3.

Uma Binomial é uma soma de variáveis 0 ou 1 (contagem de sucessos). Então, usando o TLC, uma distribuição Binomial(n,p) aproxima-se a uma distribuição Normal com os seguintes parâmetros: Normal(np, np(1-p)):

* a média da Normal é E[X] = np = {:NUMERICAL:%100%18.0:0.01}
* variância da Normal é Var[X] = np(1-p) = **7.2**

Usando esta distribuição aproximada,

P(X menor ou igual a **20** | \(X \sim_\text{aprox.} \text{Normal}\)) = {:NUMERICAL:%100%0.7719717298748721:0.01}.

Costuma-se usar a seguintes regras que sugerem que a probabilidades calculadas pela Binomial e pela Normal são próximas:

* média da Binomial = \(np \ge 5\) que {:MULTICHOICE_S:%100%se verifica\~%0%não se verifica}, e,
* variância da Binomial = \(np(1-p) \ge 5\) que {:MULTICHOICE_S:%100%se verifica\~%0%não se verifica},
* \(n \ge 30 \) que {:MULTICHOICE_S:%100%se verifica\~%0%não se verifica} (regra usual do TLC),



### feedback



#(Consulte o docente das suas turmas ou uma OT.)




## variante 010 (data row is 02)

A probabilidade de acerto no alvo é p=**0.6**.

A variável aleatória

X = "número de acertos no tiro ao alvo em n=**20** tiros"

é modelada por uma distribuição Binomial(n,p). 

Então,

P(X menor ou igual a **14** | \(X \sim \text{Binomial}\)) = {:NUMERICAL:%100%0.8744010272769627:0.01}.

O conceito seguinte têm aplicação no Capítulo 3.

Uma Binomial é uma soma de variáveis 0 ou 1 (contagem de sucessos). Então, usando o TLC, uma distribuição Binomial(n,p) aproxima-se a uma distribuição Normal com os seguintes parâmetros: Normal(np, np(1-p)):

* a média da Normal é E[X] = np = {:NUMERICAL:%100%12.0:0.01}
* variância da Normal é Var[X] = np(1-p) = {:NUMERICAL:%100%4.800000000000001:0.01}

Usando esta distribuição aproximada,

P(X menor ou igual a **14** | \(X \sim_\text{aprox.} \text{Normal}\)) = {:NUMERICAL:%100%0.8193447857369106:0.01}.

Costuma-se usar a seguintes regras que sugerem que a probabilidades calculadas pela Binomial e pela Normal são próximas:

* média da Binomial = \(np \ge 5\) que {:MULTICHOICE_S:%100%se verifica\~%0%não se verifica}, e,
* variância da Binomial = \(np(1-p) \ge 5\) que **não se verifica**,
* \(n \ge 30 \) que {:MULTICHOICE_S:%0%se verifica\~%100%não se verifica} (regra usual do TLC),



### feedback



#(Consulte o docente das suas turmas ou uma OT.)


